MyMusicStore/MyMusicStore/Controllers/MyStoreController.cs
using MyMusicStore.Filters;
using MyMusicStore.Services;
using System.Web.Mvc;
using Microsoft.Practices.Unity;
using Unity.Mvc3;

namespace MyMusicStore.Controllers
{

    [MyNewCAF(Order = 1)]
    [CustomActionFilter(Order = 2)]
    public class MyStoreController : Controller
    {
        private IStoreService service;

        public MyStoreController(IStoreService service)
        {
            this.service = service;
        }

        // GET: /Store/
        public ActionResult Details(int id)
        {
            var album = this.service.GetAlbum(id);
            if (album == null)
            {
                return this.HttpNotFound();
            }

            return this.View(album);
        }

        public ActionResult Browse(string genre)
        {
            // Retrieve Genre and its Associated Albums from database
            var genreModel = this.service.GetGenreByName(genre);

            return this.View(genreModel);
        }

        public ActionResult Index()
        {
            var genres = this.service.GetGenres();

            return this.View(genres);
        }

        // GET: /Store/GenreMenu
        public ActionResult GenreMenu()
        {
            var genres = this.service.GetGenres(9);

            return this.PartialView(genres);
        }

    }
}

MyMusicStore/MyMusicStore/Controllers/MyStoreMgrController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using MyMusicStore.Models;

namespace MyMusicStore.Controllers
{
    public class MyStoreMgrController : Controller
    {
        private MusicStoreEntities db = new MusicStoreEntities();

        //
        // GET: /MyStoreMgr/

        public ActionResult Index()
        {
            var albums = this.db.Albums.Include(a => a.Genre)
                                    .Include(a => a.Artist)
                                    .OrderBy(p => p.Price);

            return this.View(albums.ToList());
        }

        //
        // GET: /MyStoreMgr/Details/5

        //public ActionResult Details(int id = 0)
        //{
        //    Album album = db.Albums.Find(id);
        //    if (album == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(album);
        //}

        //
        // GET: /MyStoreMgr/Create

        public ActionResult Create()
        {
            this.ViewBag.GenreId = new SelectList(this.db.Genres, "GenreId", "Name");
            this.ViewBag.ArtistId = new SelectList(this.db.Artists, "ArtistId", "Name");

            return this.View();
        }

        //
        // POST: /MyStoreMgr/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Album album)
        {
            if (ModelState.IsValid)
            {
                this.db.Albums.Add(album);
                this.db.SaveChanges();

                return this.RedirectToAction("Index");
            }

            this.ViewBag.GenreId = new SelectList(this.db.Genres, "GenreId", "Name", album.GenreId);
            this.ViewBag.ArtistId = new SelectList(this.db.Artists, "ArtistId", "Name", album.ArtistId);

            return this.View(album);
        }

        //
        // GET: /MyStoreMgr/Edit/5

        public ActionResult Edit(int id)
        {
            Album album = this.db.Albums.Find(id);

            if (album == null)
            {
                return this.HttpNotFound();
            }

            this.ViewBag.GenreId = new SelectList(this.db.Genres, "GenreId", "Name", album.GenreId);
            this.ViewBag.ArtistId = new SelectList(this.db.Artists, "ArtistId", "Name", album.ArtistId);

            return this.View(album);
        }

        //
        // POST: /MyStoreMgr/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Album album)
        {
            if (ModelState.IsValid)
            {
                this.db.Entry(album).State = EntityState.Modified;
                this.db.SaveChanges();

                return this.RedirectToAction("Index");
            }

            this.ViewBag.GenreId = new SelectList(this.db.Genres, "GenreId", "Name", album.GenreId);
            this.ViewBag.ArtistId = new SelectList(this.db.Artists, "ArtistId", "Name", album.ArtistId);

            return this.View(album);
        }

        //
        // GET: /MyStoreMgr/Delete/5

        public ActionResult Delete(int id)
        {
            Album album = this.db.Albums.Find(id);

            if (album == null)
            {
                return this.HttpNotFound();
            }

            return this.View(album);
        }

        //
        // POST: /MyStoreMgr/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, FormCollection collection)
        {
            Album album = this.db.Albums.Find(id);
            this.db.Albums.Remove(album);
            this.db.SaveChanges();

            return this.RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MyMusicStore/MyMusicStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My MVC4 Music Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">@Html.ActionLink("My MVC4 Music Store", "Index", "Home")</p>
            </div>
            <div class="float-right">
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Store Mgr", "Index", "MyStoreMgr")</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div id="body">
        @{Html.RenderAction("GenreMenu", "MyStore");}
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p><a href="http://mvcmusicstore.codeplex.com">mvcmusicstore.codeplex.com</a></p>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>